import React, { useState } from 'react';
import { DemoSection } from './components/DemoSection';
import { CodeSection } from './components/CodeSection';
import { EyeIcon, CodeIcon } from './icons';

function App() {
  const [activeTab, setActiveTab] = useState<'demo' | 'code'>('demo');

  return (
    <div className="min-h-screen bg-black text-white selection:bg-blue-500/30 pb-20">
      {/* Header */}
      <header className="border-b border-zinc-800 bg-zinc-950/50 backdrop-blur sticky top-0 z-50">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-gradient-to-tr from-blue-600 to-purple-600 rounded-lg flex items-center justify-center font-bold text-lg">
              T
            </div>
            <h1 className="font-bold text-xl tracking-tight">Threads Video Pro <span className="text-zinc-500 font-normal text-sm ml-2">Extension Builder</span></h1>
          </div>
          
          <div className="flex bg-zinc-900 p-1 rounded-lg border border-zinc-800">
            <button
              onClick={() => setActiveTab('demo')}
              className={`flex items-center gap-2 px-4 py-1.5 rounded-md text-sm font-medium transition-all ${
                activeTab === 'demo' 
                  ? 'bg-zinc-800 text-white shadow-sm' 
                  : 'text-zinc-400 hover:text-white'
              }`}
            >
              <EyeIcon className="w-4 h-4" />
              Preview
            </button>
            <button
              onClick={() => setActiveTab('code')}
              className={`flex items-center gap-2 px-4 py-1.5 rounded-md text-sm font-medium transition-all ${
                activeTab === 'code' 
                  ? 'bg-zinc-800 text-white shadow-sm' 
                  : 'text-zinc-400 hover:text-white'
              }`}
            >
              <CodeIcon className="w-4 h-4" />
              Get Code
            </button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="px-6 pt-8">
        <div className="text-center mb-10">
          <h2 className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-white to-zinc-500 mb-4">
            Master your Threads feed.
          </h2>
          <p className="text-zinc-400 max-w-xl mx-auto text-lg">
            Threads videos lack basic controls. Use this tool to generate a custom browser extension that adds speed, seek, and volume controls to every video.
          </p>
        </div>

        {activeTab === 'demo' ? <DemoSection /> : <CodeSection />}
      </main>

      {/* Footer */}
      <footer className="mt-20 border-t border-zinc-900 py-8 text-center text-zinc-600 text-sm">
        <p>Generated by Gemini • React + TypeScript + Tailwind</p>
      </footer>
    </div>
  );
}

export default App;